### PR TITLE
Peer-to-peer web audio streaming

### PR DESCRIPTION
**Pull request by diegodorado**
This PR adds a mechanism for P2P audio streaming from within the web client. A user can stream audio input (Mic or another input device, if using SoundFlower/Blackhole/Virtual Audiocable/Voicemeeter Banana), and other peers can listen to that stream. The initiator streams to all peers directly via WebRTC.

### CODE REVIEW

**Comment by munshkr** [comment]
I really like this! I would extract the https server because I think it's unrelated to this PR and there's already an issue about this (#28).

**Comment by diegodorado** [comment]
You are right ... but nto sure how to proceed...should I remove that commit from the branch?

**Comment by diegodorado** [comment]
i could also update the readme with instructions on how to use it

**Comment by munshkr** [comment]
Let me see if I can reuse your code for https serving, and merge it to master. In that case I'll ask you to rebase or merge master your branch.

If you want to add instructions that would be cool!

**Comment by munshkr** [comment]
I've just merged this into master manually (had to remove the SSL commit), thanks!! :smiley: 

I tried locally and works great. I found that sometimes you can hear some weird audio compression artifacts, would be interesting if this can be optionally disabled (I'd keep it on as default).

**Comment by diegodorado** [comment]
Nice!!

**Pull request closed without merging**
