### PR TITLE
add strudel/codemirror to prepare highlighting

### PR DESCRIPTION
**Pull request by felixroos**
aiming to add highlighting support to flok for strudel editors.

- [x] add `@strudel/codemirror` package
- [x] get a reference to the current codemirror instance in `afterEval`
- [x] add an animation frame loop to highlight active haps for each strudel editor

### CODE REVIEW

**Comment by felixroos** [comment]
image

got the basic thing working :) now only a matter of finding a good start / stop mechanism

**Comment by munshkr** [comment]
Maybe you can use a `useEffect` in `useStrudel` hook to "mount/unmount" the request animation loop? The logic could live in the StrudelWrapper class but called there.

**Comment by felixroos** [comment]
> Maybe you can use a `useEffect` in `useStrudel` hook to "mount/unmount" the request animation loop? The logic could live in the StrudelWrapper class but called there.

it's never unmounted so it will never be stopped. right now it will be started when `inititalize()` (strudel-wrapper) is called, which happens on the first evaluation, which is not too bad i guess.

another problem i've noticed is that the docId might not match the editor index, so it can happen that the first editor is docId 2 and the second docId 1. Is there a way to get the index of editorRef from a docId?

**Comment by munshkr** [comment]
> > Maybe you can use a `useEffect` in `useStrudel` hook to "mount/unmount" the request animation loop? The logic could live in the StrudelWrapper class but called there.
> 
> it's never unmounted so it will never be stopped. right now it will be started when `inititalize()` (strudel-wrapper) is called, which happens on the first evaluation, which is not too bad i guess.

Ahh I see.. sounds good!

> another problem i've noticed is that the docId might not match the editor index, so it can happen that the first editor is docId 2 and the second docId 1. Is there a way to get the index of editorRef from a docId?

You could pass down to `useStrudel` the `documents` list (besides `editorRefs`), this will contain the list of the documents in the session. You could then find the index using the `docId` like this: `const editorId = documents.findIndex(doc => doc.id === docId)`.

**Comment by felixroos** [comment]
> You could pass down to `useStrudel` the `documents` list (besides `editorRefs`), this will contain the list of the documents in the session. You could then find the index using the `docId` like this: `const editorId = documents.findIndex(doc => doc.id === docId)`.

got it, i could even reuse the session to retrieve the documents! so i think this should be usable now

**Review by munshkr — APPROVED** [review]

**Comment by munshkr** [comment]
Thank you!!

**Comment by felixroos** [comment]
> Thank you!!

my pleasure :)

**Pull request merged**
