### PR TITLE
[chore] Bump to React 19

### LINKED ISSUE #306: [chore] Bump to React 19
Normally I wouldn't bother but React 19 removes the need for `forwardRef` which flok uses a lot because of juggling different UIs and editors. So it might make it easier to do more fixes, improvements, etc

https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop

### PR DESCRIPTION
**Pull request by TodePond**
Closes #306

Normally I wouldn't bother updating but React 19 removes the need for `forwardRef` which flok uses a lot because of juggling different UIs and editors. So it might make it easier to do more fixes, improvements, etc.

https://react.dev/blog/2024/12/05/react-19#ref-as-a-prop

I came across this while working on #305 

This PR
- Bumps react
- Bumps all radix packages
- Replaces all `forwardRef`s to using `ref` as a prop

No worries if this isn't wanted! But I hope you see the appeal and I think it could help future work :) Lemme know!

### CODE REVIEW

**Comment by felixroos** [comment]
i haven't used react 19 alot yet but they say it's stable so why not!

**Review by reckter — APPROVED** [review]
Looks good to me :)

**Comment by munshkr** [comment]
I had a couple of type errors when building because `ref` is marked as required prop on `Button` and `Input`, so I made them optional.

```diff
diff --git a/packages/web/src/components/ui/button.tsx b/packages/web/src/components/ui/button.tsx
index 67c464a..bb72199 100644
--- a/packages/web/src/components/ui/button.tsx
+++ b/packages/web/src/components/ui/button.tsx
@@ -35,7 +35,7 @@ const buttonVariants = cva(
 export interface ButtonProps
   extends React.ButtonHTMLAttributes<HTMLButtonElement>,
     VariantProps<typeof buttonVariants> {
-  ref: React.Ref<HTMLButtonElement>;
+  ref?: React.Ref<HTMLButtonElement>;
 }

 const Button = ({ className, variant, size, ref, ...props }: ButtonProps) => {
diff --git a/packages/web/src/components/ui/input.tsx b/packages/web/src/components/ui/input.tsx
index 8e0da2d..cd4bbf8 100644
--- a/packages/web/src/components/ui/input.tsx
+++ b/packages/web/src/components/ui/input.tsx
@@ -4,7 +4,7 @@ import { cn } from "@/lib/utils";

 export interface InputProps
   extends React.InputHTMLAttributes<HTMLInputElement> {
-  ref: React.Ref<HTMLInputElement>;
+  ref?: React.Ref<HTMLInputElement>;
 }

 const Input = ({ className, ref, ...props }: InputProps) => {
```

@TodePond do you think this will be fine?

**Comment by munshkr** [comment]
Just went ahead and merge it. Thanks again!

**Comment by TodePond** [comment]
amazing! and im not sure, i can take a look after christmas if no one else beats me to it :) seems to work(!?)

**Comment by TodePond** [comment]
@munshkr for the record, yes you did the right thing!

I'll make a pull request to add a check command to make sure I don't miss these things in the future

**Pull request merged**
