### PR TITLE
Sandbox web languages using iframes

### LINKED ISSUE #193: When creating a new session, it should stop all web targets in the session (hydra, strudel, mercury etc.)
Probably the easiest and safest way to unload and start anew is to fully refresh the session page, so that global variables are also cleaned up (at least until #239 is addressed)

### LINKED ISSUE #239: Evaluate web targets in their own sandboxes
Hydra, Strudel and Mercury all pollute the global scope (window), which causes one language to override the other languages global variables. See #232 and #182 for specific reports of this problem.

### PR DESCRIPTION
**Pull request by munshkr**
Fixes #239 

Load web libraries in separate pages and embed them using iframes. This way, these libraries do not pollute the global Window from the session page and there are no collisions between the globals each library define.

Incidentally, this also fixes #193: Because the web language libraries are only loaded inside the iframe and thus in a separate JS context, when unloading the Iframe DOM element, sound and visuals stop.

Strudel also adds some extensions to the Codemirror editor and has an animation frame to update decorators. For some reason, these updates need to run in the same context as the editor, and can't be modified from within the Iframe page.

### CODE REVIEW

**Comment by tmhglnd** [comment]
I would have to investigate but currently mercury-web throws a `mercury error` randomly when you evaluate but there is no clear indication why/where it is coming from and the code is actually still working and sound is running.

**Comment by munshkr** [comment]
> I would have to investigate but currently mercury-web throws a `mercury error` randomly when you evaluate but there is no clear indication why/where it is coming from and the code is actually still working and sound is running.

Ah, yes, I know what this is about. Will fix it soon.

**Comment by munshkr** [comment]
@tmhglnd fixed now

**Comment by tmhglnd** [comment]
Yes all good now!

**Comment by tmhglnd** [comment]
Ah I spoke a bit too soon. Because now the `m` variable in Hydra that I made global for mercury audio analysis doesn't seem to work anymore. It gives `ReferenceError: m is not defined`

**Comment by munshkr** [comment]
> Ah I spoke a bit too soon. Because now the `m` variable in Hydra that I made global for mercury audio analysis doesn't seem to work anymore. It gives `ReferenceError: m is not defined`
> 
> Edit: I see you already made an issue for this in #272

Ouch, I knew I was forgetting something. Yes, I noticed about this (was thinking of another case..), but I was thinking on solving this in #272

**Pull request merged**
